---
- name: Add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add repo for nodesource
  apt_repository: repo='deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' state=present

- name: Update apt cache
  apt: update_cache=yes

- name: Update OS
  apt: upgrade=dist force=yes